# Generated by Django 5.2.4 on 2025-07-26 16:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='spiceroute_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='spiceroute_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_option', models.CharField(choices=[('instant', 'Instant Delivery'), ('tomorrow_morning', 'Tomorrow Morning (9 AM-12 PM)'), ('tomorrow_evening', 'Tomorrow Evening (5 PM-8 PM)'), ('day_after_morning', 'Day After Morning'), ('day_after_evening', 'Day After Evening')], max_length=50)),
                ('scheduled_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.TextField()),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], max_length=50)),
                ('is_co_vendor_order', models.BooleanField(default=False)),
                ('co_vendor_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supplier_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location_pincode', models.CharField(max_length=10)),
                ('location_address', models.TextField()),
                ('business_registration_details', models.TextField(blank=True, null=True)),
                ('storage_capacity_sqft', models.IntegerField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vendor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('location_pincode', models.CharField(max_length=10)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('type_of_food', models.CharField(blank=True, max_length=100, null=True)),
                ('average_rating_as_seller', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews_as_seller', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_granted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_period_days', models.IntegerField(choices=[(2, '2 Days'), (7, '1 Week'), (14, '2 Weeks'), (30, '1 Month')])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_to_repay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursement_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted')], default='active', max_length=50)),
                ('last_repayment_date', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='spiceroute.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='spiceroute.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilogram'), ('gram', 'Gram'), ('piece', 'Piece'), ('bunch', 'Bunch'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('dozen', 'Dozen')], max_length=50)),
                ('current_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('quality_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('ai_suggested_min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ai_suggested_max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='spiceroute.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_offered', to='spiceroute.supplierprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spiceroute.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiceroute.product')),
            ],
        ),
        migrations.CreateModel(
            name='UpstreamSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('average_rating_by_msh', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews_by_msh', models.IntegerField(default=0)),
                ('msh_suppliers', models.ManyToManyField(related_name='upstream_suppliers', to='spiceroute.supplierprofile')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to='spiceroute.supplierprofile'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('is_moderated', models.BooleanField(default=False)),
                ('reviewed_upstream_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received_from_msh', to='spiceroute.upstreamsupplier')),
                ('reviewed_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='spiceroute.supplierprofile')),
                ('reviewer_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given_by_msh', to='spiceroute.supplierprofile')),
                ('reviewer_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='spiceroute.vendorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_placed', to='spiceroute.vendorprofile'),
        ),
        migrations.CreateModel(
            name='LeftoverListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilogram'), ('gram', 'Gram'), ('piece', 'Piece'), ('bunch', 'Bunch'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('dozen', 'Dozen')], max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('fresh', 'Fresh'), ('good_for_1_day', 'Good for 1 Day'), ('slightly_imperfect', 'Slightly Imperfect but Usable')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leftover_images/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pickup_delivery_preference', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=50)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('buyer_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_as_buyer', to='spiceroute.vendorprofile')),
                ('seller_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_as_seller', to='spiceroute.vendorprofile')),
            ],
        ),
    ]
