# Generated by Django 5.2.4 on 2025-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_to_repay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_period_days',
            field=models.IntegerField(choices=[(2, '2 Days'), (5, '5 Days'), (7, '1 Week'), (14, '2 Weeks'), (30, '1 Month')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('active', 'Active'), ('repaid', 'Repaid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted')], default='pending', max_length=50),
        ),
    ]
