# Generated by Django 5.2.4 on 2025-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiceroute', '0002_alter_loan_amount_to_repay_alter_loan_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftoverlisting',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gram', 'Gram'), ('piece', 'Piece'), ('bunch', 'Bunch'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('dozen', 'Dozen'), ('unit', 'Unit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality_grade',
            field=models.CharField(choices=[('grade_a', 'Grade A'), ('grade_b', 'Grade B'), ('standard', 'Standard Quality'), ('premium', 'Premium'), ('organic', 'Organic Certified')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gram', 'Gram'), ('piece', 'Piece'), ('bunch', 'Bunch'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('dozen', 'Dozen'), ('unit', 'Unit')], max_length=50),
        ),
    ]
